baseURL: 'https://www.gnuradio.org/'
languageCode: en-us
title: "GNU Radio"
theme: gnuradio-bootstrap
description: GNU Radio Project
permalink: 'https://www.gnuradio.org/'
copyright: 'The GNU Radio Foundation, Inc. All rights reserved.'
enableRobotsTXT: true
assetDir: assets/
summaryLength: 20
taxonomies:
  tag: tags
  category: categories
preserveTaxonomyNames: true
params:
  navbarBgColorClass: navbar-dark bg-dark
  secondarynavbarBgColorClass: navbar-dark bg-dark
  twitter: gnuradio
  carousel:
    enable: true
  defaults:
    imgurl: imgs/fosphor.jpg
    thumbnail: imgs/gr_web.svg
  thumbnails:
    default: imgs/gr_web.svg
    gsoc: imgs/gsoc.png
    conference: imgs/conference_web.svg
    gr_release: imgs/gr_release_web.svg
    volk_release: imgs/volk_release_web.svg
    pybombs_release: imgs/pybombs_release_web.svg
outputs:
  home:
    - html
    - amp
  section:
    - html
    - rss
menu:
  main:
    - identifier: about
      name: About
      weight: 10
    - identifier: about_GR
      name: GNU Radio
      url: /about/
      parent: about
      weight: 11
    - identifier: about_org
      name: Leadership
      url: /about/organization/
      parent: about
      weight: 12
    - identifier: blog
      name: Blog
      url: /blog/
      weight: 20
    - identifier: news
      name: News
      url: /news/
      weight: 30
    - identifier: docs
      name: Documentation
      url: /docs/
      weight: 40 
    - identifier: events
      name: Events
      weight: 50
    - identifier: events_grcon_18
      name: GNU Radio Conference 2018
      url: /grcon/grcon18/
      parent: events
      weight: 51
    - identifier: events_grcon
      name: Previous GNU Radio Conferences
      url: /grcon/
      parent: events
      weight: 52
    - identifier: events_other
      name: Other events
      url: /events/
      parent: events
      weight: 53
    - name: getting started
      url: https://wiki.gnuradio.org/index.php/WhatIsGR
      weight: 60
  grcon/grcon18:
    - identifier: grcon18
      name: GRCon18
      url: /grcon/grcon18
      weight: 10
    - identifier: presentations
      name: Presentations
      url: /grcon/grcon18/presentations
      weight: 20
