baseURL = "https://www.gnuradio.org/"
languageCode = "en-us"
title = "GNU Radio - Home Page"
theme = "gnuradio-bootstrap"
description = "GNU Radio Project"
permalink = "https://www.gnuradio.org/"
copyright = "The GNU Radio Foundation, Inc. All rights reserved."


[params]
    navbarBgColorClass = "navbar-dark bg-dark"
    twitter = "gnuradio"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    weight = -110

  [[menu.main]]
    identifier = "about_GR"
    name = "GNU Radio"
    url = "/about/"
    parent = "about"
    weight = -100

  [[menu.main]]
    identifier = "about_org"
    name = "Leadership"
    url = "/about/organization/"
    parent = "about"
    weight = -99

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = -109

  [[menu.main]]
    identifier = "news"
    name = "News"
    url = "/news/"
    weight = -108

  [[menu.main]]
    identifier = "events"
    name = "Events"
    weight = -107

  [[menu.main]]
    identifier = "events_grcon_18"
    name = "GNU Radio Conference 2018"
    url = "/grcon-2018/"
    parent = "events"
    weight = -100

  [[menu.main]]
    identifier = "events_other"
    name = "Other events"
    url = "/events/"
    parent = "events"
    weight = -90

  [[menu.main]]
    name = "getting started"
    url = "/getting-started/"
    weight = -100
