baseURL: 'https://www.gnuradio.org/'
languageCode: en-us
title: GNU Radio - Home Page
theme: gnuradio-bootstrap
description: GNU Radio Project
permalink: 'https://www.gnuradio.org/'
copyright: 'The GNU Radio Foundation, Inc. All rights reserved.'
assetDir: assets/
summaryLength: 20
params:
  navbarBgColorClass: navbar-dark bg-dark
  twitter: gnuradio
  carousel:
    enable: true
  defaults:
    imgurl: imgs/fosphor.jpg
    thumbnail: imgs/gr_web.svg
  thumbnails:
    default: imgs/gr_web.svg
    gsoc: imgs/gsoc.png
    conference: imgs/conference_web.svg
    gr_release: imgs/gr_release_web.svg
    volk_release: imgs/volk_release_web.svg
    pybombs_release: imgs/pybombs_release_web.svg
menu:
  main:
    - identifier: about
      name: About
      weight: -110
    - identifier: about_GR
      name: GNU Radio
      url: /about/
      parent: about
      weight: -100
    - identifier: about_org
      name: Leadership
      url: /about/organization/
      parent: about
      weight: -99
    - identifier: blog
      name: Blog
      url: /blog/
      weight: -109
    - identifier: news
      name: News
      url: /news/
      weight: -108
    - identifier: events
      name: Events
      weight: -107
    - identifier: events_grcon_18
      name: GNU Radio Conference 2018
      url: /grcon18/
      parent: events
      weight: -100
    - identifier: events_other
      name: Other events
      url: /events/
      parent: events
      weight: -90
    - name: getting started
      url: /getting-started/
      weight: -100
  grcon18:
    - name: GRCon2018
      url: /grcon18/
      weight: -100
    - identifier: content
      name: Content
      url: /grcon18/content
      weight: 0
    - identifier: content_pres
      name: Presentations
      url: /grcon18/presentations
      parent: content
      weight: 0
