version: 2.0
jobs:
  build:
    docker:
      - image: gnuradio/hugo:latest
    steps:
      - run: 'eval $(ssh-agent -s)'
      - add_ssh_keys:
          fingerprints:
            - "4c:3f:96:5d:63:cd:34:dd:7e:67:26:52:f9:80:a0:73"
      - run: 'mkdir -p ~/.ssh'
      - run: 'chmod 700 ~/.ssh'
      - run: 'echo "$KNOWN_HOSTS" > ~/.ssh/known_hosts'
      - run: 'chmod 644 ~/.ssh/known_hosts'
      - checkout
      - run: 'hugo version'
      - run: 'hugo -b https://test.gnuradio.org/ --minify --noTimes'
      - run: 'echo $(date +%Y.%m.%d)'
      - run: 'tar cz public | ssh $SSH_USER@$SSH_HOST "mkdir -p /data/static/test.gnuradio.org/$(date +%Y.%m.%d); cd /data/static/test.gnuradio.org/$(date +%Y.%m.%d); tar --strip-components=1 xz; rm -I /data/static/test.gnuradio.org/live; ln -sf /data/static/test.gnuradio.org/$(date +%Y.%m.%d) /data/static/test.gnuradio.org/live;"'
